apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: anhdiepmmk/kub-demo-users:v1
          env:
            - name: AUTH_HOST
              value: "localhost:80"
        - name: auth
          image: anhdiepmmk/kub-demo-auth:latest