apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: anhdiepmmk/kub-demo-users:v3
          env:
            - name: AUTH_HOST
              # value: "10.100.159.98:80"
              value: "auth-service.default"